### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by JunNanLYS** [la-vie-est-belle/qtbox#1]
QPushButton和QProgressBar点击后会导致程序崩溃，暂时不知道什么原因

**Comment by la-vie-est-belle** [comment]
你好，可能是style部分的某些控件使用了drawRoundedRect()函数或者drawArc()函数，而传入的参数不符合导致（需要int，但传入了float）。我会在下个版本中修复这个问题。感谢反馈。

**Comment by la-vie-est-belle** [comment]
v.1.1.3版本中已修复
