### ISSUE TITLE
high resolution is not adapt

### ISSUE THREAD

**Issue by panhaovue** [la-vie-est-belle/qtbox#2]
![image](https://user-images.githubusercontent.com/33897480/223003743-8fe759a2-03d5-449b-80cc-2620a362259e.png)
high resolution is not adapt

**Comment by la-vie-est-belle** [comment]
Looks awful. I will make the window resizable in next version. Also, the size of icons will be fixed, too.

**Comment by la-vie-est-belle** [comment]
Hi, I've made the window resizable. Press on the right/bottom border and then move the mouse.  Qt Box will write the current size into the config.file, and when you open the window next time, the size you set will be read.

**Comment by panhaovue** [comment]
I think you has misunderstood my word, please take a look at the picture I provided, the buttons and text of qtbox are smaller than normal window.
![image](https://user-images.githubusercontent.com/33897480/226090737-391210f6-1a15-43a6-ab53-ed1c891f9f04.png)

**Comment by panhaovue** [comment]
This is because pyqt5 is not adapted to high resolution screens
You can add the following code to solve it
QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
before:
![image](https://user-images.githubusercontent.com/33897480/226091455-8a4d4169-b648-4736-91c6-fbfe405be99c.png)
after:
![image](https://user-images.githubusercontent.com/33897480/226091393-af084f5f-a69d-4273-b8a1-c6c698741d39.png)

**Comment by la-vie-est-belle** [comment]
Thank you very much for your advice. I will put the code into Qt Box in the next version.

**Comment by la-vie-est-belle** [comment]
just updated, thanks again.
